# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docEditfileEdit.ui'
#
# Created: Mon Nov 24 18:30:24 2014
# by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 639)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.webView = QtWebKitWidgets.QWebView(Form)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout_3.addWidget(self.webView)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.editWidth = QtWidgets.QLineEdit(Form)
        self.editWidth.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.editWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.editWidth.setObjectName("editWidth")
        self.horizontalLayout_2.addWidget(self.editWidth)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.editHeight = QtWidgets.QLineEdit(Form)
        self.editHeight.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.editHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.editHeight.setObjectName("editHeight")
        self.horizontalLayout_2.addWidget(self.editHeight)
        self.comboBoxUnits = QtWidgets.QComboBox(Form)
        self.comboBoxUnits.setObjectName("comboBoxUnits")
        self.comboBoxUnits.addItem("")
        self.comboBoxUnits.addItem("")
        self.comboBoxUnits.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxUnits)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editFile = QtWidgets.QLineEdit(Form)
        self.editFile.setObjectName("editFile")
        self.horizontalLayout.addWidget(self.editFile)
        self.btnSelectFile = QtWidgets.QPushButton(Form)
        self.btnSelectFile.setObjectName("btnSelectFile")
        self.horizontalLayout.addWidget(self.btnSelectFile)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxAlign = QtWidgets.QComboBox(Form)
        self.comboBoxAlign.setObjectName("comboBoxAlign")
        self.comboBoxAlign.addItem("")
        self.comboBoxAlign.addItem("")
        self.comboBoxAlign.addItem("")
        self.verticalLayout.addWidget(self.comboBoxAlign)
        self.checkBoxFloat = QtWidgets.QCheckBox(Form)
        self.checkBoxFloat.setObjectName("checkBoxFloat")
        self.verticalLayout.addWidget(self.checkBoxFloat)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.editTitle = QtWidgets.QLineEdit(Form)
        self.editTitle.setObjectName("editTitle")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.editTitle)
        self.editAlt = QtWidgets.QLineEdit(Form)
        self.editAlt.setObjectName("editAlt")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.editAlt)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBoxHRef = QtWidgets.QComboBox(Form)
        self.comboBoxHRef.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxHRef.setEditable(True)
        self.comboBoxHRef.setObjectName("comboBoxHRef")
        self.comboBoxHRef.addItem("")
        self.comboBoxHRef.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxHRef)
        self.checkboxHrefNewWindow = QtWidgets.QCheckBox(Form)
        self.checkboxHrefNewWindow.setObjectName("checkboxHrefNewWindow")
        self.verticalLayout_2.addWidget(self.checkboxHrefNewWindow)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.formLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "x"))
        self.comboBoxUnits.setItemText(0, _translate("Form", "%"))
        self.comboBoxUnits.setItemText(1, _translate("Form", "px"))
        self.comboBoxUnits.setItemText(2, _translate("Form", "em"))
        self.label_2.setText(_translate("Form", "Größe"))
        self.btnSelectFile.setText(_translate("Form", "Auswählen"))
        self.label.setText(_translate("Form", "Datei"))
        self.comboBoxAlign.setItemText(0, _translate("Form", "Links"))
        self.comboBoxAlign.setItemText(1, _translate("Form", "Mitte"))
        self.comboBoxAlign.setItemText(2, _translate("Form", "Rechts"))
        self.checkBoxFloat.setText(_translate("Form", "FolgendenText umfließen lassen"))
        self.label_4.setText(_translate("Form", "Ausrichtung"))
        self.label_5.setText(_translate("Form", "Titel"))
        self.label_6.setText(_translate("Form", "Alternativ-Text"))
        self.label_7.setText(_translate("Form", "Verknüpfen mit"))
        self.comboBoxHRef.setItemText(0, _translate("Form", "-Keine Verlinkung-"))
        self.comboBoxHRef.setItemText(1, _translate("Form", "Vergrößern"))
        self.checkboxHrefNewWindow.setText(_translate("Form", "In neuem Fenster öffnen"))


from PyQt5 import QtWebKitWidgets
