# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extendedNumberSearchPlugin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.value1Label = QtWidgets.QLabel(Form)
        self.value1Label.setObjectName("value1Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.value1Label)
        self.value1 = QtWidgets.QSpinBox(Form)
        self.value1.setObjectName("value1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value1)
        self.value2Label = QtWidgets.QLabel(Form)
        self.value2Label.setObjectName("value2Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.value2Label)
        self.value2 = QtWidgets.QSpinBox(Form)
        self.value2.setObjectName("value2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setTitle(_translate("Form", "Filter Name"))
        self.value1Label.setText(_translate("Form", "Value 1"))
        self.value2Label.setText(_translate("Form", "Value 2"))
