# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rawtextedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rawTextEditWindow(object):
    def setupUi(self, rawTextEditWindow):
        rawTextEditWindow.setObjectName("rawTextEditWindow")
        rawTextEditWindow.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(rawTextEditWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(rawTextEditWindow)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.btnSave = QtWidgets.QPushButton(rawTextEditWindow)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)

        self.retranslateUi(rawTextEditWindow)
        QtCore.QMetaObject.connectSlotsByName(rawTextEditWindow)

    def retranslateUi(self, rawTextEditWindow):
        _translate = QtCore.QCoreApplication.translate
        rawTextEditWindow.setWindowTitle(_translate("rawTextEditWindow", "Form"))
        self.btnSave.setText(_translate("rawTextEditWindow", "Apply"))
