# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docEdit.ui'
#
# Created: Mon Nov 24 18:30:24 2014
# by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DocEdit(object):
    def setupUi(self, DocEdit):
        DocEdit.setObjectName("DocEdit")
        DocEdit.resize(531, 543)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(DocEdit)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnImport = QtWidgets.QPushButton(DocEdit)
        self.btnImport.setObjectName("btnImport")
        self.verticalLayout.addWidget(self.btnImport)
        self.treeWidget = QtWidgets.QTreeWidget(DocEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.treeWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Structure")
        self.verticalLayout.addWidget(self.treeWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnNewHeading = QtWidgets.QPushButton(DocEdit)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/actions/text/headline_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewHeading.setIcon(icon)
        self.btnNewHeading.setObjectName("btnNewHeading")
        self.gridLayout.addWidget(self.btnNewHeading, 0, 0, 1, 1)
        self.btnNewImage = QtWidgets.QPushButton(DocEdit)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/actions/text/image_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewImage.setIcon(icon1)
        self.btnNewImage.setObjectName("btnNewImage")
        self.gridLayout.addWidget(self.btnNewImage, 1, 0, 1, 1)
        self.btnNewText = QtWidgets.QPushButton(DocEdit)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/actions/text/text_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewText.setIcon(icon2)
        self.btnNewText.setObjectName("btnNewText")
        self.gridLayout.addWidget(self.btnNewText, 0, 1, 1, 1)
        self.btnSave = QtWidgets.QPushButton(DocEdit)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/success.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon3)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 3, 0, 1, 2)
        self.btnNewTable = QtWidgets.QPushButton(DocEdit)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/actions/text/table_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewTable.setIcon(icon4)
        self.btnNewTable.setObjectName("btnNewTable")
        self.gridLayout.addWidget(self.btnNewTable, 1, 1, 1, 1)
        self.boxExtensions = QtWidgets.QGroupBox(DocEdit)
        self.boxExtensions.setObjectName("boxExtensions")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.boxExtensions)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.boxExtensions)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cbExtensions = QtWidgets.QComboBox(self.widget)
        self.cbExtensions.setObjectName("cbExtensions")
        self.verticalLayout_3.addWidget(self.cbExtensions)
        self.btnAddExtension = QtWidgets.QPushButton(self.widget)
        self.btnAddExtension.setObjectName("btnAddExtension")
        self.verticalLayout_3.addWidget(self.btnAddExtension)
        self.verticalLayout_2.addWidget(self.widget)
        self.gridLayout.addWidget(self.boxExtensions, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea = QtWidgets.QScrollArea(DocEdit)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 253, 527))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(DocEdit)
        QtCore.QMetaObject.connectSlotsByName(DocEdit)

    def retranslateUi(self, DocEdit):
        _translate = QtCore.QCoreApplication.translate
        DocEdit.setWindowTitle(_translate("DocEdit", "Form"))
        self.btnImport.setText(_translate("DocEdit", "Import/Export"))
        self.treeWidget.setSortingEnabled(False)
        self.btnNewHeading.setText(_translate("DocEdit", "New caption"))
        self.btnNewImage.setText(_translate("DocEdit", "New Image"))
        self.btnNewText.setText(_translate("DocEdit", "New Text"))
        self.btnSave.setText(_translate("DocEdit", "Apply"))
        self.btnNewTable.setText(_translate("DocEdit", "New Table"))
        self.boxExtensions.setTitle(_translate("DocEdit", "Extensions"))
        self.btnAddExtension.setText(_translate("DocEdit", "Add"))

