# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginform.ui'
#
# Created: Sat May 11 13:50:18 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(480, 622)
        LoginWindow.setMinimumSize(QtCore.QSize(480, 0))
        LoginWindow.setMaximumSize(QtCore.QSize(480, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/viur_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        self.logincentralwidget = QtGui.QWidget(LoginWindow)
        self.logincentralwidget.setObjectName("logincentralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.logincentralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblImage = QtGui.QLabel(self.logincentralwidget)
        self.lblImage.setMinimumSize(QtCore.QSize(420, 254))
        self.lblImage.setMaximumSize(QtCore.QSize(420, 254))
        self.lblImage.setText("")
        self.lblImage.setPixmap(QtGui.QPixmap("icons/login.png"))
        self.lblImage.setScaledContents(True)
        self.lblImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblImage.setObjectName("lblImage")
        self.horizontalLayout_2.addWidget(self.lblImage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.lblPortal = QtGui.QLabel(self.logincentralwidget)
        self.lblPortal.setMinimumSize(QtCore.QSize(60, 0))
        self.lblPortal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPortal.setObjectName("lblPortal")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblPortal)
        self.lblUrl = QtGui.QLabel(self.logincentralwidget)
        self.lblUrl.setMinimumSize(QtCore.QSize(60, 0))
        self.lblUrl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUrl.setObjectName("lblUrl")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblUrl)
        self.editUrl = QtGui.QLineEdit(self.logincentralwidget)
        self.editUrl.setText("")
        self.editUrl.setObjectName("editUrl")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.editUrl)
        self.lblApikey = QtGui.QLabel(self.logincentralwidget)
        self.lblApikey.setMinimumSize(QtCore.QSize(60, 0))
        self.lblApikey.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblApikey.setObjectName("lblApikey")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblApikey)
        self.lblUsername = QtGui.QLabel(self.logincentralwidget)
        self.lblUsername.setMinimumSize(QtCore.QSize(60, 0))
        self.lblUsername.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblUsername)
        self.editUsername = QtGui.QLineEdit(self.logincentralwidget)
        self.editUsername.setText("")
        self.editUsername.setObjectName("editUsername")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.editUsername)
        self.lblPassword = QtGui.QLabel(self.logincentralwidget)
        self.lblPassword.setMinimumSize(QtCore.QSize(60, 0))
        self.lblPassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lblPassword)
        self.editPassword = QtGui.QLineEdit(self.logincentralwidget)
        self.editPassword.setText("")
        self.editPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.editPassword.setObjectName("editPassword")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.editPassword)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbPortal = QtGui.QComboBox(self.logincentralwidget)
        self.cbPortal.setEnabled(True)
        self.cbPortal.setMinimumSize(QtCore.QSize(0, 32))
        self.cbPortal.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.cbPortal.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.cbPortal.setObjectName("cbPortal")
        self.horizontalLayout.addWidget(self.cbPortal)
        self.startAccManagerBTN = QtGui.QPushButton(self.logincentralwidget)
        self.startAccManagerBTN.setMinimumSize(QtCore.QSize(0, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/modules/account_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startAccManagerBTN.setIcon(icon1)
        self.startAccManagerBTN.setObjectName("startAccManagerBTN")
        self.horizontalLayout.addWidget(self.startAccManagerBTN)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCaptcha = QtGui.QLabel(self.logincentralwidget)
        self.lblCaptcha.setObjectName("lblCaptcha")
        self.verticalLayout.addWidget(self.lblCaptcha)
        self.editCaptcha = QtGui.QLineEdit(self.logincentralwidget)
        self.editCaptcha.setObjectName("editCaptcha")
        self.verticalLayout.addWidget(self.editCaptcha)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.verticalLayout)
        self.label = QtGui.QLabel(self.logincentralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cbLanguages = QtGui.QComboBox(self.logincentralwidget)
        self.cbLanguages.setObjectName("cbLanguages")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbLanguages)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.btnLogin = QtGui.QPushButton(self.logincentralwidget)
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 64))
        self.btnLogin.setCursor(QtCore.Qt.PointingHandCursor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/actions/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogin.setIcon(icon2)
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout_2.addWidget(self.btnLogin)
        LoginWindow.setCentralWidget(self.logincentralwidget)
        self.menubar = QtGui.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setObjectName("menubar")
        self.menuInfo = QtGui.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuEinstellungen = QtGui.QMenu(self.menubar)
        self.menuEinstellungen.setObjectName("menuEinstellungen")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)
        self.actionErste_Schritte = QtGui.QAction(LoginWindow)
        self.actionErste_Schritte.setObjectName("actionErste_Schritte")
        self.actionHelp = QtGui.QAction(LoginWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(LoginWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtGui.QAction(LoginWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAccountmanager = QtGui.QAction(LoginWindow)
        self.actionAccountmanager.setObjectName("actionAccountmanager")
        self.menuInfo.addAction(self.actionHelp)
        self.menuInfo.addSeparator()
        self.menuInfo.addAction(self.actionAbout)
        self.menuEinstellungen.addAction(self.actionAccountmanager)
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menubar.addAction(self.menuEinstellungen.menuAction())

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        LoginWindow.setWindowTitle(QtGui.QApplication.translate("LoginWindow", "ViurAdmin – Hello!", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPortal.setText(QtGui.QApplication.translate("LoginWindow", "Portal", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUrl.setText(QtGui.QApplication.translate("LoginWindow", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.lblApikey.setText(QtGui.QApplication.translate("LoginWindow", "Captcha", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsername.setText(QtGui.QApplication.translate("LoginWindow", "User", "xy<", QtGui.QApplication.UnicodeUTF8))
        self.lblPassword.setText(QtGui.QApplication.translate("LoginWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.startAccManagerBTN.setText(QtGui.QApplication.translate("LoginWindow", "Accountmannager", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCaptcha.setText(QtGui.QApplication.translate("LoginWindow", "Not required", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LoginWindow", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogin.setText(QtGui.QApplication.translate("LoginWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInfo.setTitle(QtGui.QApplication.translate("LoginWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEinstellungen.setTitle(QtGui.QApplication.translate("LoginWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionErste_Schritte.setText(QtGui.QApplication.translate("LoginWindow", "Erste Schritte", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("LoginWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("LoginWindow", "About this Software", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("LoginWindow", "Generel settigs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAccountmanager.setText(QtGui.QApplication.translate("LoginWindow", "Accountmanager", None, QtGui.QApplication.UnicodeUTF8))

