# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginform.ui'
#
# Created: Mon Nov 24 18:30:24 2014
# by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(480, 622)
        LoginWindow.setMinimumSize(QtCore.QSize(480, 0))
        LoginWindow.setMaximumSize(QtCore.QSize(480, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/viur_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        self.logincentralwidget = QtWidgets.QWidget(LoginWindow)
        self.logincentralwidget.setObjectName("logincentralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.logincentralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblImage = QtWidgets.QLabel(self.logincentralwidget)
        self.lblImage.setMinimumSize(QtCore.QSize(420, 254))
        self.lblImage.setMaximumSize(QtCore.QSize(420, 254))
        self.lblImage.setText("")
        self.lblImage.setPixmap(QtGui.QPixmap("icons/login.png"))
        self.lblImage.setScaledContents(True)
        self.lblImage.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lblImage.setObjectName("lblImage")
        self.horizontalLayout_2.addWidget(self.lblImage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.lblPortal = QtWidgets.QLabel(self.logincentralwidget)
        self.lblPortal.setMinimumSize(QtCore.QSize(60, 0))
        self.lblPortal.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblPortal.setObjectName("lblPortal")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblPortal)
        self.lblUrl = QtWidgets.QLabel(self.logincentralwidget)
        self.lblUrl.setMinimumSize(QtCore.QSize(60, 0))
        self.lblUrl.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblUrl.setObjectName("lblUrl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblUrl)
        self.editUrl = QtWidgets.QLineEdit(self.logincentralwidget)
        self.editUrl.setText("")
        self.editUrl.setObjectName("editUrl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.editUrl)
        self.lblApikey = QtWidgets.QLabel(self.logincentralwidget)
        self.lblApikey.setMinimumSize(QtCore.QSize(60, 0))
        self.lblApikey.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblApikey.setObjectName("lblApikey")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblApikey)
        self.lblUsername = QtWidgets.QLabel(self.logincentralwidget)
        self.lblUsername.setMinimumSize(QtCore.QSize(60, 0))
        self.lblUsername.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblUsername)
        self.editUsername = QtWidgets.QLineEdit(self.logincentralwidget)
        self.editUsername.setText("")
        self.editUsername.setObjectName("editUsername")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.editUsername)
        self.lblPassword = QtWidgets.QLabel(self.logincentralwidget)
        self.lblPassword.setMinimumSize(QtCore.QSize(60, 0))
        self.lblPassword.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblPassword)
        self.editPassword = QtWidgets.QLineEdit(self.logincentralwidget)
        self.editPassword.setText("")
        self.editPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPassword.setObjectName("editPassword")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.editPassword)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbPortal = QtWidgets.QComboBox(self.logincentralwidget)
        self.cbPortal.setEnabled(True)
        self.cbPortal.setMinimumSize(QtCore.QSize(0, 32))
        self.cbPortal.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.cbPortal.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.cbPortal.setObjectName("cbPortal")
        self.horizontalLayout.addWidget(self.cbPortal)
        self.startAccManagerBTN = QtWidgets.QPushButton(self.logincentralwidget)
        self.startAccManagerBTN.setMinimumSize(QtCore.QSize(0, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/accounts.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startAccManagerBTN.setIcon(icon1)
        self.startAccManagerBTN.setObjectName("startAccManagerBTN")
        self.horizontalLayout.addWidget(self.startAccManagerBTN)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCaptcha = QtWidgets.QLabel(self.logincentralwidget)
        self.lblCaptcha.setObjectName("lblCaptcha")
        self.verticalLayout.addWidget(self.lblCaptcha)
        self.editCaptcha = QtWidgets.QLineEdit(self.logincentralwidget)
        self.editCaptcha.setObjectName("editCaptcha")
        self.verticalLayout.addWidget(self.editCaptcha)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.label = QtWidgets.QLabel(self.logincentralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cbLanguages = QtWidgets.QComboBox(self.logincentralwidget)
        self.cbLanguages.setObjectName("cbLanguages")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbLanguages)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.btnLogin = QtWidgets.QPushButton(self.logincentralwidget)
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 64))
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/actions/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogin.setIcon(icon2)
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout_2.addWidget(self.btnLogin)
        LoginWindow.setCentralWidget(self.logincentralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setObjectName("menubar")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuEinstellungen = QtWidgets.QMenu(self.menubar)
        self.menuEinstellungen.setObjectName("menuEinstellungen")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)
        self.actionErste_Schritte = QtWidgets.QAction(LoginWindow)
        self.actionErste_Schritte.setObjectName("actionErste_Schritte")
        self.actionHelp = QtWidgets.QAction(LoginWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(LoginWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(LoginWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAccountmanager = QtWidgets.QAction(LoginWindow)
        self.actionAccountmanager.setObjectName("actionAccountmanager")
        self.menuInfo.addAction(self.actionHelp)
        self.menuInfo.addSeparator()
        self.menuInfo.addAction(self.actionAbout)
        self.menuEinstellungen.addAction(self.actionAccountmanager)
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menubar.addAction(self.menuEinstellungen.menuAction())

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "ViurAdmin – Hello!"))
        self.lblPortal.setText(_translate("LoginWindow", "Portal"))
        self.lblUrl.setText(_translate("LoginWindow", "Server"))
        self.lblApikey.setText(_translate("LoginWindow", "Captcha"))
        self.lblUsername.setText(_translate("LoginWindow", "User", "xy<"))
        self.lblPassword.setText(_translate("LoginWindow", "Password"))
        self.startAccManagerBTN.setText(_translate("LoginWindow", "Accountmannager"))
        self.lblCaptcha.setText(_translate("LoginWindow", "Not required"))
        self.label.setText(_translate("LoginWindow", "Language"))
        self.btnLogin.setText(_translate("LoginWindow", "Login"))
        self.menuInfo.setTitle(_translate("LoginWindow", "Info"))
        self.menuEinstellungen.setTitle(_translate("LoginWindow", "Settings"))
        self.actionErste_Schritte.setText(_translate("LoginWindow", "Erste Schritte"))
        self.actionHelp.setText(_translate("LoginWindow", "Help"))
        self.actionAbout.setText(_translate("LoginWindow", "About this Software"))
        self.actionSettings.setText(_translate("LoginWindow", "Generel settigs"))
        self.actionAccountmanager.setText(_translate("LoginWindow", "Accountmanager"))

